CarDetector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("detector.urls")),
]

detector/urls.py
from django.urls import path
from detector.views import ImageUploader, ModelChooser, ImagePreviewer

app_name = "detector"

urlpatterns = [
    path('', ImageUploader.as_view(), name="image-uploader"),
    path('model/', ModelChooser.as_view(), name="model-chooser"),
    path('preview/', ImagePreviewer.as_view(), name="image-previewer"),
]

detector/models.py
from django.db import models


class Upload(models.Model):
    image = models.ImageField()

detector/models/manager.py
import numpy
from detector.models.yolo import Yolo
from detector.models.pretrained_pytorch.model import PretrainedModel


class ModelManager:
    """
    A class for all models management.

    Parameters:
        model_name (str): The name of the model that will perform detection on given image
    """
    def __init__(self, model_name: str):
        self.model_name = model_name
        self.is_detection_successful = False

    def perform_detection_on(self, numpy_image: numpy.ndarray) -> tuple[str, int]:
        """
        Chooses the right one model and performs detecton on given image

        Parameters:
            numpy_image (numpy.ndarray): An image in numpy array format
        """
        if self.model_name in Yolo.AVAILABLE_MODELS:
            yolo = Yolo()
            return self._perform_detection(yolo, numpy_image)
        elif self.model_name in PretrainedModel.AVAILABLE_MODELS.keys():
            pretrained_model = PretrainedModel()
            return self._perform_detection(pretrained_model, numpy_image)
        else:
            raise PretrainedModelNotFoundError(f"Given model name: {self.model_name} has not been found.")

    def _perform_detection(self, initialized_model: any, numpy_image: numpy.ndarray) -> tuple[str, int]:
        initialized_model.load(self.model_name)
        rendered_image, number_of_detections = initialized_model.perform_detection_on(numpy_image)
        self.is_detection_successful = initialized_model.is_detection_successfully_performed
        return rendered_image, number_of_detections


class PretrainedModelNotFoundError(Exception):
    pass

detector/forms.py
from django import forms

class DetectionModelForm(forms.Form):
    CHOICES = [
               ('frcnn-resnet', 'Faster R-CNN - ResNet-50'),
               ('high-res-frcnn-mobilenet', 'Faster R-CNN - MobileNetV3-Large'),
               ('low-res-frcnn-mobilenet', 'Faster R-CNN - MobileNetV3-Large (mobile)'),
               ('fcos-resnet', 'FCOS - ResNet-50'),
               ('ssd300', 'SSD300'),
               ('ssdlite-mobilenet', 'SSDLite - MobileNetV3'),
               ('yolov5n', 'YOLOv5 (nano)'),
               ('yolov5s', 'YOLOv5 (small)'),
               ('yolov5m', 'YOLOv5 (medium)'),
               ('yolov5l', 'YOLOv5 (large)'),
               ('yolov5x', 'YOLOv5 (extra large)')]

    model = forms.ChoiceField(choices=CHOICES, widget=forms.Select)


class UploadForm(forms.Form):
    image = forms.ImageField(widget=forms.FileInput(attrs={"id": "dragndrop", "accept":".png, .jpg, .jpeg"}))

detector/views.py
import json
from django.http import HttpResponse
from django.shortcuts import render, redirect
import numpy as np
from django.views import View
from django.contrib import messages
from .forms import DetectionModelForm, UploadForm
from detector.models.manager import ModelManager


class ImageUploader(View):
    uploaded_image = None

    def get(self, request):

        context = {
            'form': UploadForm()
        }

        return render(request, "detector/image_uploader.html", context)

    def post(self, request):
        form = UploadForm(request.POST, request.FILES)

        if form.is_valid():
            image = form.cleaned_data["image"]
            numpy_converted_file = np.fromstring(image.read(), np.uint8)
            ImageUploader.uploaded_image = numpy_converted_file
            return HttpResponse(json.dumps({"redirect_url": "/model/"}))  # For AJAX response
        else:
            messages.error(request, "Incorrect image-like file. Try again.")
            return HttpResponse(json.dumps({"redirect_url": "/"}))  # For AJAX response


class ModelChooser(View):
    selected_model = None

    def get(self, request):
        if ImageUploader.uploaded_image is not None:

            context = {
                "detection_model_form": DetectionModelForm()
            }

            return render(request, "detector/model_chooser.html", context=context)
        else:
            messages.error(request,"You need to upload an image first")
            return redirect("detector:image-uploader")

    def post(self, request):
        detection_model_form = DetectionModelForm(request.POST)

        if detection_model_form.is_valid():
            selected_model = detection_model_form.cleaned_data['model']
            model_manager = ModelManager(selected_model)

            try:
                rendered_image, number_of_detections = model_manager.perform_detection_on(ImageUploader.uploaded_image)
            except Exception:
                messages.error(request, "An error occured during detection. Check your image and try again.")
                return redirect("detector:image-uploader")

            ImagePreviewer.rendered_image = rendered_image
            ImagePreviewer.number_of_detections = number_of_detections
            return redirect("detector:image-previewer")
        else:
            messages.error(request, "Selected pretrained model doesn't exists. Try again.")
            return redirect("detector:image-uploader")


class ImagePreviewer(View):
    rendered_image = None
    number_of_detections = 0

    def get(self, request):
        if ImagePreviewer.rendered_image is not None:

            context = {
                "image": ImagePreviewer.rendered_image,
                "number_of_detections": ImagePreviewer.number_of_detections
            }
            return render(request, "detector/image_previewer.html", context=context)

        else:
            messages.error(request, "You need to upload an image first")
            return redirect("detector:image-uploader")

detector/templates/detector/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/png" href="{% static 'detector/favicon/favicon_car.ico' %}"/>
    <link rel="stylesheet" href="{% static 'detector/css/base_style.css' %}">
    <link rel="stylesheet" href="{% static 'detector/css/horizontal_progress_bar_style.css' %}">
    <title>{% block title %}{% endblock %}</title>
    {% block head %}
    {% endblock %}
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

detector/templates/detector/file_uploader.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Upload file</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'detector/css/file_uploader_style.css' %}">
    <link rel="stylesheet" href="{% static 'detector/css/horizontal_progress_bar_style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<style>
    .not-visible{
        display: none;
    }
</style>
<body>
<div class="navigation_menu" id="navigation_menu">
  <ul class="navigation_tabs" id="navigation_tabs">
    <li class="tab_active">
        Upload image
    </li>
    <li class="tab_disabled">
        Choose pretrained model
    </li>
    <li class="tab_disabled">
        Perform detection
    </li>
    <li class="tab_disabled">
        Check result
    </li>
  </ul>
</div>
<h1>Upload an image</h1>
    <form method="post" id="upload-form">
        {% csrf_token %}
        {{form.image}}
        <p>Select an image or drag it here</p>
        <button type="submit">Upload</button>
    </form>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
    {% endfor %}
</ul>
{% endif %}
    <div id="progress-bar-container">
        <div class="container not-visible progress" id="progress">
            <div class="progress-bar bg-info" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
    </div>
{#            <div class="container not-visible progress" id="progress">#}
{#    </div>#}
    <script>
          $(document).ready(function(){
      $('form input').change(function () {
          var filename = $('input[type=file]').val().split('\\').pop();
          filename = filename.toLowerCase();

          if(filename.endsWith(".png") || filename.endsWith(".jpg") || filename.endsWith(".jpeg"))
          {
              $('form p').text(filename);
          }
          else if(filename===""){
              $('form p').text("Select an image or drag it here");
          }
          else{
              $('form p').text("It is not an image-like file! Try again.");
              alert("You have uploaded a file that is not an image. Try again and make sure that your file extension is: .jpg, .jpeg or .png")
              $("#dragndrop").val('');
          }

      });
      $('#dragndrop').bind('change', function() {
          //this.files[0].size gets the size of your file.

          if(this.files[0].size === 0){
              alert("Uploaded image has a size that is equal to 0")
              $("#dragndrop").val('');
              $('form p').text("Select an image or drag it here");
          }
    });
});
        const uploadForm = document.getElementById('upload-form');
        const input_file = document.getElementById('dragndrop');
        const progress_bar = document.getElementById('progress-bar-container');

        $("#upload-form").submit(function(e){
            e.preventDefault();
            $form = $(this)
            var formData = new FormData(this);
            const media_data = input_file.files[0];
            if(media_data != null){
                console.log(media_data);
                progress_bar.classList.remove("not-visible");
            }

            $.ajax({
                type: 'POST',
                url:'/',
                data: formData,
                beforeSend: function(){

                },
                xhr:function(){
                    const xhr = new window.XMLHttpRequest();
                    xhr.upload.addEventListener('progress', e=>{
                        if(e.lengthComputable){
                            const percentProgress = (e.loaded/e.total)*100;
                            console.log(percentProgress);
                            progress_bar.innerHTML = `<div class="progress" id="progress"><div class="progress-bar progress-bar-striped"
                    role="progressbar" style="width: ${percentProgress}%" aria-valuenow="${percentProgress}" aria-valuemin="0"
                    aria-valuemax="100">${percentProgress}</div></div>`
                        }
                    });
                    return xhr
                },
                success: function(response){
                    var responseObj = JSON.parse(response);
                    uploadForm.reset()
                    window.location.href = responseObj["redirect_url"]
                },
                error: function(response){
                    var responseObj = JSON.parse(response);
                    uploadForm.reset()
                    window.location.href = responseObj
                },
                cache: false,
                contentType: false,
                processData: false,

            });
        });

    </script>
</body>
</html>

detector/templates/detector/image_previewer.html
{% extends "detector/base.html" %}
{% load static %}

{% block title %}
    Car Detector - Preview image
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'detector/css/image_previewer_style.css' %}">
{% endblock %}

{% block body %}
    <div class="navigation_menu" id="navigation_menu">
        <ul class="navigation_tabs" id="navigation_tabs">
            <li class="tab_inactive">
                <a href="{% url 'detector:image-uploader' %}">Upload image</a>
            </li>
            <li class="tab_inactive">
                <a href="{% url 'detector:model-chooser' %}">Choose pretrained model</a>
            </li>
            <li class="tab_inactive">
                Perform detection
            </li>
            <li class="tab_active">
                Check result
            </li>
        </ul>
    </div>
    <h1>Preview of your image:</h1>
    <div id="image-container">
        <img src="data:image/jpg;base64, {{ image }}" alt="Preview of image">
    </div>
    <div id="detections-number">
        {% if number_of_detections >= 1 %}
            <p>Number of detected cars: {{ number_of_detections }}</p>
        {% else %}
            <p>No cars have been detected</p>
        {% endif %}
    </div>
{% endblock %}

detector/templates/detector/image_uploader.html
{% extends 'detector/base.html' %}
{% load static %}

{% block title %}
    Car Detector - Upload an image
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'detector/css/image_uploader_style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
{% endblock %}
{% block body %}
    <div class="navigation_menu" id="navigation_menu">
        <ul class="navigation_tabs" id="navigation_tabs">
            <li class="tab_active">
                Upload image
            </li>
            <li class="tab_disabled">
                Choose pretrained model
            </li>
            <li class="tab_disabled">
                Perform detection
            </li>
            <li class="tab_disabled">
                Check result
            </li>
        </ul>
    </div>
    <h1>Upload an image</h1>
        <form method="post" id="upload-form">
            {% csrf_token %}
            {{form.image}}
            <p>Select an image or drag it here</p>
            <button type="submit">Upload</button>
        </form>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
            {% endfor %}
        </ul>
    {% endif %}
    <div id="progress-bar-container">
        <div class="container not-visible progress" id="progress">
            <div class="progress-bar bg-info" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
    </div>
    <script>
        $(document).ready(function()
        {
            $('form input').change(function ()
            {
              var filename = $('input[type=file]').val().split('\\').pop();
              filename = filename.toLowerCase();

              if(filename.endsWith(".png") || filename.endsWith(".jpg") || filename.endsWith(".jpeg"))
              {
                  $('form p').text(filename);
              }
              else if(filename===""){
                  $('form p').text("Select an image or drag it here");
              }
              else
              {
                  $('form p').text("It is not an image-like file! Try again.");
                  alert("You have uploaded a file that is not an image. Try again and make sure that your file extension is: .jpg, .jpeg or .png")
                  $("#dragndrop").val('');
              }
            });
            $('#dragndrop').bind('change', function()
            {
              if(this.files[0].size === 0)
              {
                  alert("Uploaded image has a size that is equal to 0 bytes.")
                  $("#dragndrop").val('');
                  $('form p').text("Select an image or drag it here");
              }
            });
        });
        const uploadForm = document.getElementById('upload-form');
        const input_file = document.getElementById('dragndrop');
        const progress_bar = document.getElementById('progress-bar-container');

        $("#upload-form").submit(function(e)
        {
            e.preventDefault();
            $form = $(this)
            var formData = new FormData(this);
            const media_data = input_file.files[0];
            if(media_data != null)
            {
                console.log(media_data);
                progress_bar.classList.remove("not-visible");
            }

            $.ajax({
                    type: 'POST',
                    url:'/',
                    data: formData,
                    beforeSend: function(){},
                    xhr:function()
                    {
                        const xhr = new window.XMLHttpRequest();
                        xhr.upload.addEventListener('progress', e=>
                        {
                            if(e.lengthComputable)
                            {
                                const percentProgress = (e.loaded/e.total)*100;
                                console.log(percentProgress);
                                progress_bar.innerHTML = `<div class="progress" id="progress"><div class="progress-bar progress-bar-striped"
                        role="progressbar" style="width: ${percentProgress}%" aria-valuenow="${percentProgress}" aria-valuemin="0"
                        aria-valuemax="100">${percentProgress}</div></div>`;
                            }
                        });
                        return xhr
                    },
                    success: function(response)
                    {
                        var responseObj = JSON.parse(response);
                        uploadForm.reset();
                        window.location.href = responseObj["redirect_url"];
                    },
                    error: function(response)
                    {
                        var responseObj = JSON.parse(response);
                        uploadForm.reset();
                        window.location.href = responseObj;
                    },
                    cache: false,
                    contentType: false,
                    processData: false,

            });
        });

        </script>
{% endblock %}

detector/templates/detector/model_chooser.html
{% extends "detector/base.html" %}
{% load static %}

{% block title %}
    Car Detector - Choose pretrained model
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'detector/css/model_chooser_style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
{% endblock %}

{% block body %}
    <div class="container-standard">
        <div class="navigation_menu" id="navigation_menu">
            <ul class="navigation_tabs" id="navigation_tabs">
                <li class="tab_inactive">
                    <a href="{% url 'detector:image-uploader' %}">Upload image</a>
                </li>
                <li class="tab_active">
                    Choose pretrained model
                </li>
                <li class="tab_disabled">
                    Perform detection
                </li>
                <li class="tab_disabled">
                    Check result
                </li>
            </ul>
        </div>
        <h1>Choose pretrained model</h1>
            <form method="POST" id="models-form">
                {% csrf_token %}
                <div class="select">
                    {% for element in detection_model_form %}
                        <p>{{ element }}</p>
                    {% endfor %}
                </div>
                <button type="submit">Continue</button>
            </form>
    </div>
    <div class="container-loading hideme">
        <div class="navigation_menu" id="navigation_menu">
            <ul class="navigation_tabs" id="navigation_tabs">
                <li class="tab_inactive">
                    <a href="{% url 'detector:image-uploader' %}">Upload image</a>
                </li>
                <li class="tab_inactive">
                    <a href="{% url 'detector:model-chooser' %}">Choose pretrained model</a>
                </li>
                <li class="tab_active">
                    Perform detection
                </li>
                <li class="tab_disabled">
                    Check result
                </li>
            </ul>
        </div>
        <h1>Performing detection...</h1>
        <div class="loader loader--style3" title="2">
          <svg version="1.1" id="loader-1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
             width="100px" height="100px" viewBox="0 0 50 50" style="enable-background:new 0 0 50 50;" xml:space="preserve">
          <path fill="#000" d="M43.935,25.145c0-10.318-8.364-18.683-18.683-18.683c-10.318,0-18.683,8.365-18.683,18.683h4.068c0-8.071,6.543-14.615,14.615-14.615c8.072,0,14.615,6.543,14.615,14.615H43.935z">
            <animateTransform attributeType="xml"
              attributeName="transform"
              type="rotate"
              from="0 25 25"
              to="360 25 25"
              dur="0.6s"
              repeatCount="indefinite"/>
            </path>
          </svg>
        </div>
    </div>
    <script>
        // Function to hide model chooser view and show loading screen
        $("button").on("click", function() {
            $(".container-standard").addClass("hideme")
            $(".container-loading").removeClass("hideme")
        })

        // Function to change width of <select> tag to match selected content
        $('select').change(function(){
            var text = $(this).find('option:selected').text()
            var $aux = $('<select/>').append($('<option/>').text(text))
            $(this).after($aux)
            $(this).width($aux.width())
            $aux.remove()
        }).change()
    </script>
{% endblock %}